server:
  port: 8003
mybatis:
  config-location: classpath:mybatis/mybatis.xml  #mybatis配置文件
  mapper-locations: classpath:mybatis/mapper/**/*.xml  #mybatis映射文件
  type-aliases-package: com.staryea.entities  #mybatis对应的实体类目录


spring:
  application:
    name: microservice-provider-dept
#  profiles: dept-8003

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/e3mall?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-wait-millis: 60000
      initial-size: 5
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-dept-8002 #自定义初始化实例的ID
    prefer-ip-address: true #访问路径可以显示IP





info: # 展示前台页面点击微服务名称需要显示的内容
  app.name: staryea-microservice-dept-8002
  company.name: starya
  build.artifactId: $project.artifactId$
  bulid.verison: $project.verison$
