server:
  port: 80
spring:
  application:
    name: microservice-consumer-dept-80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false
  instance:
    instance-id: microservice-consumer-dept-80
    prefer-ip-address: true
