server:
  port: 80
spring:
  application:
    name: microservice-consumer-dept-feign
#  profiles: dept-feign
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-consumer-feign-dept
    prefer-ip-address: true

# 开启熔断 通过将熔断机制写在feign调用的接口上来实现拦截所有方法的熔断（类中实现所有方法的熔断机制，来实现熔断与业务的分离）
# 当使用zuul转发到feign时，目前需要启动hystrix的仪表盘的服务才能正常运行（如果使用类熔断），如果不使用类熔断，则不用
feign:
  hystrix:
    enabled: true